In [1]:
import numpy as np
import pandas as pd
import sys

### Some nn word for fun

In [2]:
class KittyNN(object):
    
    def __init__(self, learning_rate=0.15):
        self.weight_1 = np.random.normal(0.0, 1, size=(2, 3))
        self.weight_2 = np.random.normal(0.0, 1, size=(1, 2))
        self.sigmoid_map = np.vectorize(self.sigmoid)
        self.learning_rate = np.array([learning_rate])
        
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def prediction(self, inputs):
        inputs_1 = np.dot(self.weight_1, inputs)
        outputs_1 = self.sigmoid_map(inputs_1) 
        
        inputs_2 = np.dot(self.weight_2, outputs_1)
        outputs_2 = self.sigmoid_map(inputs_2)
        return outputs_2
    
    
    def train(self, inputs, answer):
        inputs_1 = np.dot(self.weight_1, inputs)
        outputs_1 = self.sigmoid_map(inputs_1) 
        
        inputs_2 = np.dot(self.weight_2, outputs_1)
        outputs_2 = self.sigmoid_map(inputs_2)
        
        predict = outputs_2[0]
        
        #Последние ребра
        error_2 = np.array([predict - answer])
        predict_der_2 = predict * (1 - predict)
        weight_delta_2 = error_2 * predict_der_2
        self.weight_2 = self.weight_2 - np.dot(weight_delta_2, outputs_1.reshape(1, len(outputs_1))) * self.learning_rate
        
        #Начальные ребра
        error_1 = weight_delta_2 * self.weight_2
        predict_der_1 = outputs_1 * (1 - outputs_1)
        weight_delta_1 = error_1 * predict_der_1
        self.weight_1 = self.weight_1 - np.dot(inputs.reshape(len(inputs), 1), weight_delta_1).T * self.learning_rate
        
def MSE(y, Y):
    return np.mean((y - Y)**2)

In [3]:
df=pd.read_csv('kitty.csv', sep=',')
df.values

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 0]], dtype=int64)

In [4]:
train = [
      ([0, 0, 0], 0),
      ([1, 1, 1], 1),
      ([1, 0, 0], 0),
      ([0, 1, 1], 1),
      ([1, 1, 0], 0),
      ([0, 0, 1], 1),
      ([0, 0, 0], 0)
]

In [5]:
a = 0.1

model = KittyNN(learning_rate=a)

##### Веса до тренировки модели

In [6]:
model.weight_1

array([[-0.44536635,  2.13321851,  0.51570878],
       [-0.43715645, -1.49492462,  1.12713958]])

In [7]:
model.weight_2

array([[0.4987972, 0.1591809]])

In [8]:
epoch = 5000

for e in range(epoch):
    inputs = []
    answers = []
    for input, answer in train:
        model.train(np.array(input), answer)
        inputs.append(input)
        answers.append(answer)
    
    train_loss = MSE(model.prediction(np.array(input).T), np.array(answer))
    sys.stdout.write("\rProgress: {}, Training loss: {}".format(str(100 * e/float(epoch))[:4], str(train_loss)[:5]))      

Progress: 99.9, Training loss: 0.003

##### Веса после тренировки модели

In [9]:
model.weight_1

array([[-1.72516417,  1.60255583,  3.13422266],
       [ 1.62797107, -1.07304075, -4.01495981]])

In [10]:
model.weight_2

array([[ 3.43596477, -8.90555931]])

In [11]:
for input_val, answer in train:
    print("For input: {} the prediction is: {}, expected: {}".format(
        input_val,
        model.prediction(input_val),
        answer
        ))
    #train_loss = model.MSE(np.array(answer), np.array(model.prediction(input_val)))
    #print(train_loss)
    


For input: [0, 0, 0] the prediction is: [0.06095101], expected: 0
For input: [1, 1, 1] the prediction is: [0.95272937], expected: 1
For input: [1, 0, 0] the prediction is: [0.00098239], expected: 0
For input: [0, 1, 1] the prediction is: [0.96615361], expected: 1
For input: [1, 1, 0] the prediction is: [0.01721317], expected: 0
For input: [0, 0, 1] the prediction is: [0.95830496], expected: 1
For input: [0, 0, 0] the prediction is: [0.06095101], expected: 0


### Шпаргалка

In [12]:
error = actual - expected
weight_delta = error * sigmoid(x)dx
sigmoid(x)dx = sigmoid(x) * (1 - sigmoid(x))

weight = weight - output * weight_delta * learning_rate

SyntaxError: invalid syntax (<ipython-input-12-79f4aa289bbe>, line 2)

In [31]:
[
      ([0, 0, 0], 0),
      ([1, 1, 1], 1),
      ([1, 0, 0], 0),
      ([0, 1, 1], 1),
      ([1, 1, 0], 0),
      ([0, 0, 1], 1),
      ([0, 0, 0], 0)
]

model.prediction([])

array([0.64351446])